- id: doi:10.1016/j.cophys.2020.07.014
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2468867320300766-gr1.jpg

- id: doi:10.7554/eLife.85012
  image: images/eelbrain.png
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/Eelbrain/Alice
    - type: website
      link: http://eelbrain.readthedocs.io/
  repo: christianbrodbeck/Eelbrain

- id: doi:10.1101/2024.02.20.580731
  image: https://www.biorxiv.org/content/biorxiv/early/2024/02/22/2024.02.20.580731/F1.large.jpg
